version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to React and its related packages
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-scripts"
